import '../models/product_model.dart';

class ProductsRepository {
  final List<Product> products = [
    Product(
      id: '1',
      title: 'Classic Beanie',
      description: 'This is a sample description.',
      price: 12.00,
      imageUrls: [],
      category: ProductCategory.clothing,
      collections: [],
    ),
    Product(
      id: '2',
      title: 'Classic Cap',
      description: 'This is a sample description.',
      price: 12.00,
      imageUrls: [],
      category: ProductCategory.clothing,
      collections: [],
    ),
    Product(
      id: '3',
      title: 'Classic Hoodie',
      description: 'This is a sample description.',
      price: 25.00,
      imageUrls: [],
      category: ProductCategory.clothing,
      collections: [],
    ),
    Product(
      id: '4',
      title: 'Classic Rainbow Hoodie',
      description: 'This is a sample description.',
      price: 12.99,
      imageUrls: [],
      originalPrice: 30.00,
      promoMessage: 'This is a sample promo message.',
      category: ProductCategory.clothing,
      collections: [],
    ),
    Product(
      id: '5',
      title: 'Classic Sweatshirt',
      description: 'This is a sample description.',
      price: 23.00,
      imageUrls: [],
      category: ProductCategory.clothing,
      collections: [],
    ),
    Product(
      id: '6',
      title: 'Classic Tee',
      description: 'This is a sample description.',
      price: 11.00,
      imageUrls: [],
      category: ProductCategory.clothing,
      collections: [],
    ),
    Product(
      id: '7',
      title: 'Essential Tee',
      description: 'This is a sample description.',
      price: 6.99,
      imageUrls: [],
      originalPrice: 10.00,
      promoMessage: 'This is a sample promo message.',
      category: ProductCategory.clothing,
      collections: [],
    ),
    Product(
      id: '8',
      title: 'Graduation Hoodie',
      description: 'This is a sample description.',
      price: 35.00,
      imageUrls: [],
      category: ProductCategory.clothing,
      collections: [],
    ),
    Product(
      id: '9',
      title: 'Signature Hoodie',
      description: 'This is a sample description.',
      price: 32.99,
      imageUrls: [],
      category: ProductCategory.clothing,
      collections: [],
    ),
    Product(
      id: '10',
      title: 'Signature Tee',
      description: 'This is a sample description.',
      price: 14.99,
      imageUrls: [],
      category: ProductCategory.clothing,
      collections: [],
    ),
    Product(
      id: '11',
      title: 'Cotton Tote Bag',
      description: 'This is a sample description.',
      price: 1.99,
      imageUrls: [],
      category: ProductCategory.merchandise,
      collections: [],
    ),
    Product(
      id: '12',
      title: 'Crested Tie',
      description: 'This is a sample description.',
      price: 10.99,
      imageUrls: [],
      originalPrice: 15.00,
      promoMessage: 'This is a sample promo message.',
      category: ProductCategory.merchandise,
      collections: [],
    ),
    Product(
      id: '13',
      title: 'Crested Tie',
      description: 'This is a sample description.',
      price: 2.50,
      imageUrls: [],
      category: ProductCategory.merchandise,
      collections: [],
    ),
    Product(
      id: '14',
      title: 'ID Holder',
      description: 'This is a sample description.',
      price: 0.75,
      imageUrls: [],
      category: ProductCategory.merchandise,
      collections: [],
    ),
    Product(
      id: '15',
      title: 'Lanyard',
      description: 'This is a sample description.',
      price: 2.75,
      imageUrls: [],
      category: ProductCategory.merchandise,
      collections: [],
    ),
    Product(
      id: '16',
      title: 'Portsmouth City Magnet',
      description: 'This is a sample description.',
      price: 4.50,
      imageUrls: [],
      category: ProductCategory.merchandise,
      collections: [],
    ),
    Product(
      id: '17',
      title: 'Pen',
      description: 'This is a sample description.',
      price: 1.00,
      imageUrls: [],
      category: ProductCategory.merchandise,
      collections: [],
    ),
    Product(
      id: '18',
      title: 'Portsmouth City Postcard',
      description: 'This is a sample description.',
      price: 1.00,
      imageUrls: [],
      category: ProductCategory.merchandise,
      collections: [],
    ),
    Product(
      id: '19',
      title: 'Rainbow Lanyard',
      description: 'This is a sample description.',
      price: 2.75,
      imageUrls: [],
      category: ProductCategory.merchandise,
      collections: [],
    ),
    Product(
      id: '20',
      title: '8GB USB',
      description: 'This is a sample description.',
      price: 5.50,
      imageUrls: [],
      originalPrice: 7.50,
      promoMessage: 'This is a sample promo message.',
      category: ProductCategory.merchandise,
      collections: [],
    ),
  ];
}
